-- PropMeshes (ReplicatedStorage.SminskiShared.PropMeshes)
-- GENERATED by art/blender/export_buildings.py -- do not hand-edit.
-- size/offset for every sub-mesh of the city kit, in studs. offset is
-- measured from the whole piece's ground contact point.

local V = Vector3.new

return {
	["SM_Store_Corner_A_wall"] = { size = V(16.8, 14.0, 16.8), offset = V(-0.0, 7.0, 0.0) },
	["SM_Store_Floor_A_accent"] = { size = V(36.4, 8.0, 0.7), offset = V(-0.0, 6.0, -7.475) },
	["SM_Store_Floor_A_glass"] = { size = V(35.0, 6.6, 0.5), offset = V(-0.0, 6.0, -7.825) },
	["SM_Store_Floor_A_stone"] = { size = V(37.0, 0.7, 1.3), offset = V(-0.0, 1.6, -8.025) },
	["SM_Store_Floor_A_wall"] = { size = V(38.0, 12.0, 16.0), offset = V(-0.0, 6.0, 0.675) },
	["SM_Store_Ground_A_accent"] = { size = V(36.0, 17.1, 4.85), offset = V(-0.0, 11.05, -8.2) },
	["SM_Store_Ground_A_door"] = { size = V(8.0, 11.0, 0.6), offset = V(-0.0, 5.6, -5.875) },
	["SM_Store_Ground_A_glass"] = { size = V(35.0, 9.0, 0.5), offset = V(-0.0, 7.0, -5.875) },
	["SM_Store_Ground_A_stone"] = { size = V(38.8, 2.6, 18.6), offset = V(-0.0, 1.3, 1.325) },
	["SM_Store_Ground_A_wall"] = { size = V(38.0, 14.0, 16.0), offset = V(-0.0, 7.0, 2.225) },
	["SM_Store_Roof_A_accent"] = { size = V(39.6, 4.2, 17.6), offset = V(-0.0, 2.1, 0.0) },
	["SM_Store_Roof_A_metal"] = { size = V(21.54, 3.0, 4.0), offset = V(-0.09, 3.6, 1.5) },
	["SM_Store_Roof_A_stone"] = { size = V(35.6, 0.5, 13.6), offset = V(-0.0, 1.85, 0.0) },
	["bench_metal"] = { size = V(5.6, 2.0, 2.0), offset = V(-0.0, 1.0, -0.05) },
	["bench_timber"] = { size = V(6.0, 1.975, 2.1), offset = V(-0.0, 2.7125, 0.0) },
	["bikerack_wall"] = { size = V(7.0, 2.8028, 0.4916), offset = V(-0.0, 1.3999, 0.0) },
	["bush_leaf"] = { size = V(4.8986, 2.992, 4.3818), offset = V(0.35, 1.496, 0.0) },
	["bush_leaf2"] = { size = V(3.2, 2.24, 3.2), offset = V(-1.2, 1.896, 0.6) },
	["flowers_accent"] = { size = V(4.0906, 1.1051, 1.898), offset = V(0.003, 0.9988, -0.0013) },
	["flowers_timber"] = { size = V(4.0, 0.6, 2.0), offset = V(-0.0, 0.3, 0.0) },
	["hydrant_wall"] = { size = V(1.6097, 3.2512, 1.4988), offset = V(-0.0014, 1.6238, -0.0) },
	["lamp_glass"] = { size = V(2.2, 2.2, 2.2), offset = V(-0.0, 14.0, 0.0) },
	["lamp_metal"] = { size = V(2.8, 15.6354, 2.8), offset = V(-0.0, 7.8167, 0.0) },
	["mailbox_wall"] = { size = V(1.9933, 4.102, 1.6), offset = V(-0.0, 2.0486, 0.0) },
	["pine_leaf"] = { size = V(14.0, 12.072, 14.0), offset = V(-0.0, 11.656, 0.0) },
	["pine_leaf2"] = { size = V(10.8, 17.056, 10.8), offset = V(0.0, 18.892, -0.0) },
	["pine_timber"] = { size = V(2.1636, 8.0, 2.1636), offset = V(0.0, 4.0, -0.0) },
	["planter_leaf"] = { size = V(4.0, 2.8, 4.0), offset = V(-0.0, 3.4, 0.0) },
	["planter_stone"] = { size = V(5.4, 2.75, 5.4), offset = V(-0.0, 1.375, 0.0) },
	["trashcan_wall"] = { size = V(2.6502, 3.4512, 2.6472), offset = V(-0.0, 1.7251, -0.0015) },
	["tree_leaf"] = { size = V(13.2, 10.08, 12.0), offset = V(0.8, 11.5, 0.0) },
	["tree_leaf2"] = { size = V(12.1, 12.47, 8.5), offset = V(-1.35, 12.315, 1.35) },
	["tree_timber"] = { size = V(1.7636, 8.0, 1.7636), offset = V(0.2, 4.0, 0.0) },
}
