#!/usr/bin/env python3
"""Inventory a directory of extracted third-party model kits.

WHY THIS IS IN THE REPO. The kits themselves are not: they are ~73 MB of OBJ
and FBX, and docs/INVENTORY.md's rule is that templates live in the .rbxl, not
in git. What has to be versioned is the RECORD -- which objects exist, how big
they are, and whether each one can legally and technically ship. Re-run this
whenever a kit is added and commit the manifest it writes.

Counts triangles from the OBJ (an n-vertex face is n-2 triangles), because the
Roblox MeshPart limit is the one hard gate on whether an asset can be imported
at all, and guessing it from file size is not good enough.

    python3 tools/kit_manifest.py ~/Downloads/newassets/_x docs/KITS.md
"""
import os, sys, glob

TRI_LIMIT = 10_000  # Roblox MeshPart hard cap


def tris(path):
    n = 0
    try:
        with open(path, "r", errors="ignore") as f:
            for line in f:
                if line.startswith("f "):
                    n += max(1, len(line.split()) - 3)
    except OSError:
        return -1
    return n


def licence(kit_dir):
    for p in glob.glob(f"{kit_dir}/**/*icen*.txt", recursive=True) + \
             glob.glob(f"{kit_dir}/**/*icense*", recursive=True):
        try:
            txt = open(p, errors="ignore").read()
        except OSError:
            continue
        if "CC0" in txt or "Creative Commons Zero" in txt:
            return "CC0"
        return "see " + os.path.basename(p)
    return "UNKNOWN -- do not ship until checked"


def main(root, out):
    rows = []
    for kit in sorted(os.listdir(root)):
        d = os.path.join(root, kit)
        if not os.path.isdir(d):
            continue
        objs = sorted(glob.glob(f"{d}/**/*.obj", recursive=True))
        if not objs:
            continue
        items = [(os.path.basename(p)[:-4], tris(p)) for p in objs]
        items = [i for i in items if i[1] >= 0]
        rows.append((kit, licence(d), items))

    with open(out, "w") as f:
        f.write("# Third-party model kits\n\n")
        f.write("Generated by `tools/kit_manifest.py` -- do not hand-edit.\n\n")
        f.write("The kit files are NOT in this repo (~73 MB of OBJ/FBX). This is the\n")
        f.write("record of what exists and whether it can ship. See `docs/INVENTORY.md`\n")
        f.write("for the curation procedure and `.claude/rules/assets.md` for the review\n")
        f.write("every one of these still owes.\n\n")
        f.write(f"Every mesh below is checked against the Roblox MeshPart limit of "
                f"{TRI_LIMIT:,} triangles.\n\n")
        f.write("| kit | licence | meshes | total tris | biggest | over limit |\n")
        f.write("|---|---|---|---|---|---|\n")
        for kit, lic, items in rows:
            tot = sum(t for _, t in items)
            big = max(items, key=lambda i: i[1])
            over = [i for i in items if i[1] > TRI_LIMIT]
            f.write(f"| {kit} | {lic} | {len(items)} | {tot:,} | {big[0]} "
                    f"({big[1]:,}) | {len(over)} |\n")
        f.write("\n---\n")
        for kit, lic, items in rows:
            f.write(f"\n## {kit}\n\n`{lic}`\n\n")
            f.write(" · ".join(f"`{n}`" for n, _ in sorted(items)))
            f.write("\n")
    print(f"{sum(len(i) for _, _, i in rows)} meshes across {len(rows)} kits -> {out}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "docs/KITS.md")
